language: python
dist: xenial
sudo: true

python: 
  - 3.8

services:
  - postgresql

addons:
  postgresql: '12.4'

env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov

